version: '0.0.{build}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
clone_folder: c:\projects\AlpineSkiHouse
branches:
  only:
    - master
skip_tags: true
cache:
  - packages -> **\packages.config
platform:
  - x64
  - Any CPU
configuration: Release
test:
  assemblies:
    - '**\*.tests.dll'
before_build:
  - dotnet restore **\*.sln
build_script:
  - ps: ./Build.ps1
